from enum import StrEnum


class ModerationAction(StrEnum):
    USER_WARN = "USER_WARN"
    USER_SUSPEND = "USER_SUSPEND"
    USER_BAN = "USER_BAN"
    USER_UNBAN = "USER_UNBAN"
    USER_UNSUSPEND = "USER_UNSUSPEND"
    REMOVE_FROM_CHANNEL = "REMOVE_FROM_CHANNEL"
    MESSAGE_DELETE = "MESSAGE_DELETE"
    CHANNEL_LOCK = "CHANNEL_LOCK"
    CHANNEL_UNLOCK = "CHANNEL_UNLOCK"


ROLE_LEVELS = {"member": 1, "moderator": 2, "admin": 3}
MAX_REASON_LENGTH = 1000
MAX_SUSPENSION_SECONDS = 365 * 24 * 60 * 60
MAX_BAN_SECONDS = 365 * 24 * 60 * 60
